# -*- coding: utf-8 -*-
"""Edge_preparation_4class.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DAoJPLlllwLpHo6cpLrGbQVU0_HuNPW3
"""

#mounting on drive
from google.colab import drive
drive.mount('/content/drive',force_remount=True)

import cv2
from google.colab.patches import cv2_imshow
import glob
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
from statistics import stdev,mean

edges=[]
attrs=[]
graph_id=1
node_id=1
graph_indicator=[]
node_labels=[]
graph_labels=[]

activity_map={}
activity_map[1]='COVID'
activity_map[2]='NORMAL'
activity_map[3]='PNEUMONIA_BAC'
activity_map[4]='PNEUMONIA_VIRUS'

def normalize(arr):
  arr=np.array(arr)
  m=np.mean(arr)
  s=np.std(arr)
  return (arr-m)/s

arr=[1,2,3,4,5]
print(normalize(arr))

def generate_graphs(filename,node_label,activity_map):
  print(" ... Reading image: "+filename+" ...")
  global node_id,edges,attrs,graph_id,node_labels,graph_indicator
  cnt=0
  img=cv2.imread(filename)
  #print(img.shape)
  dim1,dim2,_=img.shape
  attrs1=[]

  print("Image type: " + activity_map[node_label] + "\nPixel matrix is of: "+str(dim1)+"x"+str(dim2))
  #img=cv2.resize(img,(128,128))
  img1=img.copy()
  #dim1=128
  #dim2=128
  nodes=np.full((dim1,dim2),-1)
  edge=0
  for i in range(dim1):
    for j in range(dim2):
      b,_,_=img[i][j]
      if(b>=128):
        nodes[i][j]=node_id
        attrs1.append(b)
        graph_indicator.append(graph_id)
        node_labels.append([node_label,activity_map[node_label]])
        node_id+=1
        cnt+=1
      else:
        img1[i][j]=0
  
  for i in range(dim1):
    for j in range(dim2):
      if(nodes[i][j]!=-1):
        li=max(0,i-1)
        ri=min(i+2,dim1)
        lj=max(0,j-1)
        rj=min(j+2,dim2)
        for i1 in range(li,ri):
          for j1 in range(lj,rj):
            if((i1!=i or j1!=j) and (nodes[i1][j1]!=-1)):
              edges.append([nodes[i][j],nodes[i1][j1]])
              edge+=1
  
  attrs1=normalize(attrs1)

  '''
  print("--Original--")
  cv2_imshow(img)
  print("--graph only--")
  cv2_imshow(img1)
  '''
  attrs.extend(attrs1)
  del attrs1
  print("For given image nodes formed: "+str(cnt)+" edges formed: "+str(edge))
  if(cnt!=0): graph_id+=1

def generate_graph_with_labels(dirname,label,activity_map):
  print("\n... Reading Directory: "+dirname+" ...\n")
  global graph_labels
  filenames=glob.glob(dirname+'/*.png')
  for filename in filenames:
    generate_graphs(filename,label,activity_map)
    graph_labels.append([label,activity_map[label]])

def process_graphs(covid_dir,norm_dir,bac_dir,vir_dir,activity_map):
  global node_labels,graph_labels
  generate_graph_with_labels(covid_dir,1,activity_map)
  generate_graph_with_labels(norm_dir,2,activity_map)
  generate_graph_with_labels(bac_dir,3,activity_map)
  generate_graph_with_labels(vir_dir,4,activity_map)
  print("Processing done")
  print("Total nodes formed: "+str(len(node_labels))+"Total graphs formed: "+str(len(graph_labels)))

#working directories
covid_dir='/content/drive/My Drive/Github_4class_edge/Pretwitt/COVID' #for covid
norm_dir='/content/drive/My Drive/Github_4class_edge/Pretwitt/NORMAL' #for normal
bac_dir='/content/drive/My Drive/Github_4class_edge/Pretwitt/PNEUMONIA_BAC' #for bacterial-pneumonia
vir_dir='/content/drive/My Drive/Github_4class_edge/Pretwitt/PNEUMONIA_VIRUS' #for viral-pneumonia

process_graphs(covid_dir,norm_dir,bac_dir,vir_dir,activity_map)

print(len(node_labels))
print(len(graph_labels))
print(len(edges))
print(len(attrs))

df_A=pd.DataFrame(columns=["node-1","node-2"],data=np.array(edges))
print("Shape of edge dataframe: "+str(df_A.shape))
print("\n--summary of dataframe--\n" ,df_A.head(50))

df_node_label=pd.DataFrame(data=np.array(node_labels),columns=["label","activity-name"])
print("shape of node-label dataframe: "+str(df_node_label.shape))
print("\n--summary of dataframe--\n" ,df_node_label)

df_graph_label=pd.DataFrame(data=np.array(graph_labels),columns=["label","activity-name"])
print("shape of node-label dataframe: "+str(df_graph_label.shape))
print("\n--summary of dataframe--\n" ,df_graph_label.head(50))

df_node_attr=pd.DataFrame(data=np.array(attrs),columns=["gray-val"])
print("shape of node-attribute dataframe: "+str(df_node_attr.shape))
print("\n--summary of dataframe--\n" ,df_node_attr.head(50))

df_graph_indicator=pd.DataFrame(data=np.array(graph_indicator),columns=["graph-id"])
print("shape of graph-indicator dataframe: "+str(df_graph_indicator.shape))
print("\n--summary of dataframe--\n" ,df_graph_indicator.head(50))

df_node_label=df_node_label.drop(["activity-name"],axis=1)
print(df_node_label.head(50))

df_graph_label=df_graph_label.drop(["activity-name"],axis=1)
print(df_graph_label.head(50))

def save_dataframe_to_txt(df,filepath):
  df.to_csv(filepath,header=None,index=None,sep=',',mode='w')

sourcepath='/content/drive/My Drive/GraphTrain/dataset/Github_4class_Pretwitt/raw'

save_dataframe_to_txt(df_A,sourcepath+'/Github_4class_Pretwitt_A.txt')
save_dataframe_to_txt(df_graph_indicator,sourcepath+'/Github_4class_Pretwitt_graph_indicator.txt')
save_dataframe_to_txt(df_graph_label,sourcepath+'/Github_4class_Pretwitt_graph_labels.txt')
save_dataframe_to_txt(df_node_attr,sourcepath+'/Github_4class_Pretwitt_node_attributes.txt')
save_dataframe_to_txt(df_node_label,sourcepath+'/Github_4class_Pretwitt_node_labels.txt')

df=pd.read_csv(sourcepath+'/Kaggle_Pretwitt_graph_labels.txt',names=["label"])
print(len(df))

del node_id,node_labels,attrs,activity_map,edges,graph_indicator,graph_id,graph_labels

df=pd.read_csv('/content/drive/My Drive/GraphTrain/dataset/Kaggle_Pretwitt/raw/Kaggle_Pretwitt_graph_labels.txt',names=["label"])
'''
df=df.append(df_graph_label)
print(df.head(50),df.shape)
'''
print(len(df))